kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node:18.14.0
  pull: always
  commands:
    - pwd
    - npm i
    - npm run build
    - ls -la
      
trigger:
  branch:
    include:
      - master
  event:
    include:
      - push
